# Generated by Django 5.0.4 on 2026-05-22 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ingredient', models.BooleanField(default=False, help_text='Агар True бошад — маҳсулот дар склад нигоҳ дошта мешавад')),
                ('description', models.TextField(blank=True, default='')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingredients_text', models.JSONField(blank=True, default=list, help_text='[{"name": "...", "amount": "..."}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ingredient', models.ForeignKey(help_text='Компонент / хоммаҳсулот', on_delete=django.db.models.deletion.CASCADE, related_name='used_as_ingredient_in', to='products.product')),
                ('product', models.ForeignKey(help_text='Маҳсулоти натиҷа (масалан бургер)', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_lines', to='products.product')),
            ],
            options={
                'ordering': ['product_id', 'ingredient_id'],
            },
        ),
        migrations.CreateModel(
            name='ProductColorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'Чорранг (Black)'), ('white', 'Сафед (White)'), ('blue', 'Кабуд (Blue)'), ('purple', 'Бунафш (Purple)'), ('red', 'Сурх (Red)'), ('gold', 'Тиллоӣ (Gold)'), ('yellow', 'Зард (Yellow)'), ('pink', 'Гулобӣ (Pink)'), ('titanium', 'Титаниум (Titanium)'), ('green', 'Сабз (Green)'), ('teal', 'Феруза (Teal)'), ('ultramarine', 'Ултрамарин (Ultramarine)')], max_length=30)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_stocks', to='products.product')),
            ],
            options={
                'ordering': ['product', 'color'],
                'unique_together': {('product', 'color')},
            },
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='uniq_product_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='quantity_positive'),
        ),
    ]
