# Generated by Django 5.0.4 on 2026-06-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Нархи оптовӣ', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productcolorstock',
            name='color',
            field=models.CharField(choices=[('orange', 'Норанҷӣ (Orange)'), ('black', 'Чорранг (Black)'), ('white', 'Сафед (White)'), ('blue', 'Кабуд (Blue)'), ('purple', 'Бунафш (Purple)'), ('red', 'Сурх (Red)'), ('gold', 'Тиллоӣ (Gold)'), ('yellow', 'Зард (Yellow)'), ('pink', 'Гулобӣ (Pink)'), ('titanium', 'Титаниум (Titanium)'), ('green', 'Сабз (Green)'), ('teal', 'Феруза (Teal)'), ('ultramarine', 'Ултрамарин (Ultramarine)')], max_length=30),
        ),
    ]
