# Generated by Django 5.0.4 on 2026-06-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stocktake_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, default='', max_length=300)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=100)),
                ('telegram_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Танзимоти система',
            },
        ),
        migrations.AlterField(
            model_name='stocktakesession',
            name='status',
            field=models.CharField(choices=[('open', 'Кушода'), ('closed', 'Баста')], default='open', max_length=10),
        ),
    ]
