# Generated by Django 5.0.4 on 2026-06-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('chef', 'Chef'), ('assembler', 'Assembler')], default='cashier', max_length=20),
        ),
    ]
