# Generated by Django 5.0.4 on 2026-06-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Нархи оптовӣ ҳангоми фурӯш', max_digits=10, null=True),
        ),
    ]
