# Generated by Django 5.0.4 on 2026-06-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_add_discount_table_to_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='modifiers',
            field=models.JSONField(blank=True, default=list, help_text='[{"group": "Соусҳо", "name": "Кетчуп", "price": "2.00"}]'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='modifiers_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
